name: build-pyorbit
on: push

jobs:
  ubuntu-2004:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
         - uses: actions/checkout@v2
         - name: Install packages
           run: |
             apt update
             DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
             apt install -y build-essential python-dev libmpich-dev mpich  zlib1g-dev libfftw3-dev

         - name: Make
           run: |
             cd /__w/py-orbit/py-orbit
             cat setupEnvironment.sh
             . /__w/py-orbit/py-orbit/setupEnvironment.sh
             make clean
             make

         - name: Test
           run: |
             .github/workflows/run-tests.sh
