name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: centos:centos8
    steps:
         - uses: actions/checkout@v2
         - name: Log the node version
           run: |
             ls -alh /github/home /__w/py-orbit/py-orbit
