name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: centos:centos8
    steps:
         - uses: actions/checkout@v2
         - name: Log the node version
           run: |
             yum install -y gcc gcc-c++ make python2 python2-devel mpich mpich-devel zlib-devel fftw-devel
             ls -alh /github/home /__w/py-orbit/py-orbit
