name: build-pyorbit
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: centos:centos8
    steps:
         - uses: actions/checkout@v2
         - name: Install packages
           run: |
             yum install -y gcc gcc-c++ make python2 python2-devel mpich mpich-devel zlib-devel fftw-devel
         
         - name: Run make
           run: |
             cd /__w/py-orbit/py-orbit
             cat setupEnvironment.sh
             source /__w/py-orbit/py-orbit/setupEnvironment.sh
             make clean
             make
             cd examples/AccLattice_Tests
             ./START.sh lattice_test.py 2
